name: Deploy to Salon
on:
  push:
    branches: [main]
jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository code
        uses: actions/checkout@v3

      - name: Deploy to production
        uses: cpina/github-action-push-to-another-repository@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          source-directory: "."
          destination-github-username: "KryptoBlack"
          destination-repository-name: "coming-soon-site-2"
          user-email: patrick.thakare123@gmail.com
          target-branch: main
